version: 2.1
jobs:
  install:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: npm-install
          command: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths: node_modules

  build:
    docker:
      - image: circleci/buildpack-deps:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build docker image
          command: docker build -f DockerFile -t myapi .
      - run:
          name: Login to docker hub
          command: docker login -u ${DOCKER_USER} --password ${DOCKER_PASS}
      - run :
          name: push docker
          command: |
              docker tag myapi ${DOCKER_USER}/${PROJECT_NAME}:latest
              docker push ${DOCKER_USER}/${PROJECT_NAME}:latest

workflows:
  version: 2.1
  dev-workflow:
    jobs:
      - install
      - build

