version: 2.1
jobs:
  build:
    working_directory: ~/projet
    docker:
      - image: circleci/node:12
    steps:
      - checkout # special step to check out source code to working directory
      - run:
          name: install-npm-wee
          command: |
            npm install
            echo 'Leo le dozo'
      - save_cache: # special step to save the dependency cache
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test
#    - run: # run tests
#          name: test
#          command: npm test
