version: 2.1
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build-docker-image
          command: docker build -f DockerFile -t myapi .
workflows:
  version: 2.1
  dev-workflow:
    jobs:
      - build
#      - test
#    - run: # run tests
#          name: test
#          command: npm test
